# Generated by Django 4.0.5 on 2022-06-26 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('telefono', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
            },
        ),
        migrations.CreateModel(
            name='Inquilino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('CBU', models.CharField(blank=True, max_length=22, null=True)),
            ],
            options={
                'verbose_name': 'Inquilino',
                'verbose_name_plural': 'Inquilinos',
            },
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('telefono', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('CBU', models.CharField(blank=True, max_length=22, null=True)),
            ],
            options={
                'verbose_name': 'Propietario',
                'verbose_name_plural': 'Propietarios',
            },
        ),
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_casa', models.CharField(help_text='Ingrese el numero y la letra ej: 5A', max_length=2)),
                ('estado', models.BooleanField(choices=[('ALQ', 'Alquilada'), ('DES', 'Desocupada'), ('OCU', 'Ocupada-Dueño')], default='OCU')),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casa.administrador', verbose_name='Administrador')),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casa.inquilino', verbose_name='Inquilino')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casa.propietario', verbose_name='Propietario')),
            ],
        ),
    ]
