# Generated by Django 4.0.5 on 2022-06-26 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casa',
            options={'verbose_name': 'Casa', 'verbose_name_plural': 'Casas'},
        ),
        migrations.AlterModelOptions(
            name='propietario',
            options={'ordering': ['nombre'], 'verbose_name': 'Propietarios', 'verbose_name_plural': 'Propietarios'},
        ),
        migrations.AddField(
            model_name='casa',
            name='disponibilidad',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='casa',
            name='administrador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casa.administrador'),
        ),
        migrations.AlterField(
            model_name='casa',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casa.propietario'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Propietario'),
        ),
    ]
