# Generated by Django 4.0.5 on 2022-06-26 14:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('casa', '0002_alter_casa_options_alter_propietario_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='administrador',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='casa',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='casa',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inquilino',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquilino',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='propietario',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propietario',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='casa',
            name='estado',
            field=models.CharField(choices=[('ALQ', 'Alquilada'), ('DES', 'Desocupada'), ('OCU', 'Ocupada-Dueño')], default='OCU', max_length=3),
        ),
        migrations.AlterField(
            model_name='casa',
            name='inquilino',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='casa.inquilino', verbose_name='Inquilino'),
        ),
    ]
