# Generated by Django 4.0.5 on 2022-06-26 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casa', '0003_administrador_creado_administrador_modificado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casa',
            options={'ordering': ['numero_casa'], 'verbose_name': 'Casa', 'verbose_name_plural': 'Casas'},
        ),
        migrations.AlterField(
            model_name='administrador',
            name='apellido',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='casa',
            name='estado',
            field=models.CharField(choices=[('Alquilada', 'Alquilada'), ('Desocupada', 'Desocupada'), ('Ocupada-Dueño', 'Ocupada-Dueño')], default='OCU', max_length=15),
        ),
        migrations.AlterField(
            model_name='casa',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='casa.inquilino', verbose_name='Inquilino'),
        ),
        migrations.AlterField(
            model_name='inquilino',
            name='apellido',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='apellido',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
