# Generated by Django 4.0.5 on 2022-07-05 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casa', '0004_alter_casa_options_alter_administrador_apellido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(choices=[('01', 'Enero'), ('02', 'Febrero'), ('03', 'Marzo'), ('04', 'Abril'), ('05', 'Mayo'), ('06', 'Junio'), ('07', 'Julio'), ('08', 'Agosto'), ('09', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], default='01', max_length=15)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=4)),
                ('año', models.PositiveSmallIntegerField(max_length=4)),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
                'ordering': ['mes'],
            },
        ),
        migrations.AlterModelOptions(
            name='inquilino',
            options={'ordering': ['nombre'], 'verbose_name': 'Inquilino', 'verbose_name_plural': 'Inquilinos'},
        ),
        migrations.AlterField(
            model_name='casa',
            name='administrador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='casa.administrador'),
        ),
        migrations.AlterField(
            model_name='casa',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='casa.inquilino', verbose_name='Inquilino'),
        ),
        migrations.AlterField(
            model_name='casa',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='casa.propietario'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
    ]
