# Generated by Django 4.0.5 on 2022-07-08 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casa', '0006_cuota_creado_cuota_modificado_alter_cuota_año_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['cuota_abonada'], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
    ]
