# Generated by Django 4.0.5 on 2022-07-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casa', '0007_alter_pago_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquilino',
            name='vigencia',
            field=models.BooleanField(default=True),
        ),
    ]
